
version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
#  app:
#    build: .
#    working_dir: /go/src/app
#    command: ["go", "run", "."]
#    volumes:
#      - .:/go/src/app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    links:
#      - db